name: 'actions-steps/project-build/python'
description: 'Building python project'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: updating path
      if: hashFiles('pyproject.toml') != ''
      run: echo "~/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: building python project
      if: hashFiles('pyproject.toml') != ''
      run: poetry build
      shell: bash
