name: 'actions-steps/project-version/node'
description: 'Getting node project version'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: getting node version
      if: hashFiles('package.json') != ''
      run: |
        VERSION=$(grep 'version' package.json | cut -f2 -d":" | cut -f2 -d\")
        echo "${VERSION}" > version.txt
      shell: bash

    - uses: actions/upload-artifact@v6
      with:
        name: version
        path: version.xml
        retention-days: 1
        if-no-files-found: ignore

