name: 'actions-steps/cache-version'
description: 'Cache version files'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: getting version
      uses: actions/cache@v5
      with:
        path: version.txt
        key: ${{ runner.os }}-cache-version-${{ hashFiles('version.txt') }}
        restore-keys: ${{ runner.os }}-cache-version-
