name: 'actions-steps/project-badge'
description: 'Create project badge'
inputs:
  version:
    description: version
    required: true

  gist-id:
    description: gist id
    required: true

  gist-token:
    description: gist token
    required: true

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - uses: actions/download-artifact@v4

    - run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
      shell: bash

    - if: ${{ inputs.version }} != ''
      uses: schneegans/dynamic-badges-action@v1.8.0
      with:
        gistID: ${{ inputs.gist-id }}
        auth: ${{ inputs.gist-token }}
        filename: ${{ env.REPO_NAME }}-version.json
        label: version
        message: v${{ env.VERSION }}
        color: green

    - uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: ${{ inputs.gist-id }}
        token: ${{ inputs.gist-token }}
