name: 'actions-steps/project-badge'
description: 'Create project badge'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - uses: actions/download-artifact@v4

    - uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: ${GIST_ID}
        token: ${{ secrets.GIST_TOKEN }}
      env:
        GIST_ID: ${{ secrets.GIST_ID }}