name: 'actions-steps/project-badge'
description: 'Create project badge'
inputs:
  gist-id:
    description: gist id
    required: true

  gist-token:
    description: gist token
    required: true

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - uses: actions/download-artifact@v4
      with:
        name: version

    - if: hashFiles('version.txt') != ''
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
      shell: bash

    - run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      shell: bash

    - if: hashFiles('version.txt') != ''
      uses: schneegans/dynamic-badges-action@v1.8.0
      with:
        gistID: ${{ inputs.gist-id }}
        auth: ${{ inputs.gist-token }}
        filename: ${{ env.REPO_NAME }}-version.json
        label: version
        message: ${{ env.VERSION }}
        color: brightgreen
        forceUpdate: true
        style: flat

    - uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: ${{ inputs.gist-id }}
        token: ${{ inputs.gist-token }}
