name: 'actions-steps/project-test/maven'
description: 'Testing maven project'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: testing maven project
      if: hashFiles('pom.xml') != ''
      run: mvn test
      id: testing
      continue-on-error: true
      shell: bash

    - uses: actions/upload-artifact@v7
      with:
        name: test-results
        path: ./**/*est*esults.xml
        retention-days: 1
        if-no-files-found: ignore

    - name: testing maven project fail
      if: steps.testing.outcome == 'failure'
      run: exit 1
      shell: bash
