name: 'actions-steps/project-version/csharp'
description: 'Getting csharp project version'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: getting csharp version
      if: hashFiles('*.csproj') != ''
      run: |
        VERSION=$(dotnet build /getProperty:Version *.csproj)
        echo "${VERSION}" > version.txt
      shell: bash

    - uses: actions/upload-artifact@v7
      with:
        name: version
        path: version.txt
        retention-days: 1
        if-no-files-found: ignore

