name: 'actions-steps/project-install/python'
description: 'Installing python project'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: installing python project
      if: hashFiles('pyproject.toml') != ''
      run: pip install .[dev] --no-cache-dir --target ~/.local/libs
      shell: bash

    - name: updating path
      if: hashFiles('pyproject.toml') != ''
      run: echo "~/.local/libs/bin" >> $GITHUB_PATH
      shell: bash

    - name: creating python requirements
      if: hashFiles('pyproject.toml') != ''
      run: poetry export --without-hashes --output requirements.txt
      shell: bash
      env:
        PYTHONPATH: ~/.local/libs
