name: 'actions-steps/project-install/python'
description: 'Installing python project'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: installing python project
      if: hashFiles('pyproject.toml') != ''
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install .[dev] --no-cache-dir
      shell: bash

    - name: updating path
      if: hashFiles('pyproject.toml') != ''
      run: echo "~/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: creating python requirements
      if: hashFiles('pyproject.toml') != ''
      run: poetry export --without-hashes --output requirements.txt
      shell: bash
