name: 'actions-steps/project-install/python'
description: 'Installing python project'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: installing python project
      if: hashFiles('pyproject.toml') != ''
      run: pip install .[dev]
      shell: bash
      env:
        PIP_CACHE_DIR: ~/.cache/pip
        PIP_ROOT_USER_ACTION: ignore

    - name: updating path
      if: hashFiles('pyproject.toml') != ''
      run: echo "~/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: creating python requirements
      if: hashFiles('pyproject.toml') != ''
      run: poetry export --without-hashes --output requirements.txt
      shell: bash
