name: 'actions-steps/project-version/python'
description: 'Getting python project version'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: getting python version
      if: hashFiles('pyproject.toml') != ''
      run: |
        VERSION=$(grep -E '^version' pyproject.toml | cut -f2 -d":" | cut -f2 -d\")
        echo "${VERSION}" > version.txt
      shell: bash

    - uses: actions/upload-artifact@v6
      with:
        name: version
        path: version.txt
        retention-days: 1
        if-no-files-found: ignore

