name: 'actions-steps/project-coverage/csharp'
description: 'Coverage csharp project'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: coverage csharp project
      if: hashFiles('*.csproj') != '' && hashFiles('global.json') != ''
      run: dotnet r test:coverage
      id: coverage
      continue-on-error: true
      shell: bash

    - uses: actions/upload-artifact@v7
      with:
        name: coverage
        path: ./**/coverage
        retention-days: 1
        if-no-files-found: ignore

    - name: coverage csharp project fail
      if: steps.coverage.outcome == 'failure'
      run: exit 1
      shell: bash
