name: 'actions-steps/project-install/maven'
description: 'Installing maven project'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: installing maven project
      if: hashFiles('pom.xml') != ''
      run: mvn dependency:resolve
      shell: bash
