name: 'actions-steps/project-type'
description: 'Check project type'
outputs:
  type:
    description: "The project type value"
    value: ${{ steps.project_type.outputs.type }}

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: getting node type
      if: hashFiles('package.json') != ''
      run: |
        echo "TYPE=node" >> $GITHUB_ENV
      shell: bash

    - name: getting python type
      if: hashFiles('pyproject.toml') != ''
      run: |
        echo "TYPE=python" >> $GITHUB_ENV
      shell: bash

    - name: getting project type
      id: project_type
      run: |
        if [ -n "${{ env.TYPE }}" ]; then
          echo "type=${{ env.TYPE }}" >> $GITHUB_OUTPUT
        else
          echo "Project is not node|python"
          exit 1
        fi
      shell: bash