name: 'actions-steps/cache-dependencies'
description: 'Cache dependencies files'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: getting node dependencies
      if: hashFiles('package.json') != ''
      uses: actions/cache@v5
      with:
        path: |
          node_modules
          package-lock.json
        key: cache-dependencies

    - name: getting python dependencies
      if: hashFiles('pyproject.toml') != ''
      uses: actions/cache@v5
      with:
        path: |
          ~/.local/libs
          requirements.txt
        key: cache-dependencies

