---
name: "tagged-release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          make_latest: true
          tag_name: ${{ github.ref_name }}
      - name: Mutable tag
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | awk -F. '{print $1}')
          gh release delete ${VERSION} --yes
          gh release create ${VERSION}
        shell: bash