---
name: "release and tagged"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          name: ${{ github.ref_name }}
          make_latest: true

  tagged:
    name: tagged
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: mutable
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | awk -F. '{print $1}')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
        shell: bash
      - name: tagged
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          name: ${VERSION}
          make_latest: false
