---
name: "release and tagged"

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          make_latest: true

  version:
    name: version
    needs: release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cleaning.outputs.version }}
    steps:
      - name: cleaning
        id: cleaning
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | awk -F. '{print $1}')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        shell: bash

  cleaning:
    name: cleaning
    needs: version
    runs-on: ubuntu-latest

    steps:
      - name: cleaning
        run: |
          VERSION=${{ needs.version.outputs.version }}
          gh release delete "${VERSION}" --cleanup-tag --yes || true
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

  tagged:
    name: tagged
    needs: cleaning
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: tagged
        run: |
          VERSION=${{ needs.version.outputs.version }}
          gh release create "${VERSION}" --yes
          gh release edit ${VERSION} --tag "${{ github.ref_name }}" --latest
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
